### ISSUE TITLE
Problem converting large PDFs

### ISSUE THREAD

**Issue by oaeide** [firstlookmedia/dangerzone#58] opened 2020-03-14 23:12 UTC
When converting a large document (in my case 105 pages), it fails on page 20 on the "from pixels to searchable PDF"-step. 

Im using [this PDF from Acronis ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwjT696hjZvoAhXLk4sKHUPmD8kQFjACegQIBBAB&url=http%3A%2F%2Fdl.acronis.com%2Fu%2Fpdf%2FASD5_userguide_en-US.pdf&usg=AOvVaw2V9zRx3mMLUIxGYQZ82P_s)

**Comment by oaeide** [comment] 2020-03-14 23:13
Actually, looking at the logs, it doesn't fail, it just stops outputting the progress messages
![image](https://user-images.githubusercontent.com/1035667/76692086-c57e6300-6651-11ea-9f39-208c533cb286.png)

**Comment by oaeide** [comment] 2020-03-14 23:17
Conversion finished, but the dangerzone gui still looks the same, and I cant find any converted PDF afterwards

**Comment by micahflee** [comment] 2020-04-09 22:02
I'm not sure why your GUI didn't update, I'm not able to reproduce that part. But I did figure out why you couldn't find the converted PDF. It's because of #70 -- it finished, then timed out trying to compress it. (If you scrolled up in your terminal, you would see the timeout message.)

Since I can't reproduce the GUI problem right now I'm going to close this issue, and work on fixing #70. Feel free to re-open it if you keep hitting it.

**Closed by micahflee** 2020-04-09 22:02 UTC
